### ISSUE TITLE
support new release policy

### ISSUE THREAD

**Issue by VitaliyaIoffe** [tarantool/installer.sh#5]
According to the new release policy, we should support new paths for installer.sh:

`https://tarantool.io/QkWdyqR/release/series-2/installer.sh` and `https://tarantool.io/QkWdyqR/pre-release/series-2/installer.sh`

**Comment by Totktonada** [comment]
Don't forget about:

* Choose release / pre-release / both using an environment variable.
* Choose series-2 using the SERIES=2 environment variable (as replacement for VER=2.5/2.6/2.7/2.8). Support SERIES=1.10.

**Comment by Totktonada** [comment]
> Choose series-2 using the SERIES=2 environment variable (as replacement for VER=2.5/2.6/2.7/2.8). Support SERIES=1.10.

Or keep `VER` and support `VER=2`.
